project_id = "diayjpsrcerycycyaxst"

[functions.analyze-ergonomia]
verify_jwt = false

[functions.onboarding-signup]
verify_jwt = false

[functions.ai-plano-acao]
verify_jwt = false

[functions.ai-ouvidoria]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-epi-fiscal]
verify_jwt = false

[functions.extract-atestado]
verify_jwt = false

[functions.ai-sst-analise]
verify_jwt = false

[functions.ai-feedback]
verify_jwt = false

[functions.advertencia-link]
verify_jwt = false

[functions.ai-cultura-manual]
verify_jwt = false

[functions.ai-cultura-sugestao]
verify_jwt = false
