import { 
  TrendingDown, 
  Clock, 
  AlertTriangle, 
  MessageSquareWarning, 
  Heart,
  Minus,
  RefreshCw,
  Target,
  Smile,
  Users,
  Zap,
  Sparkles,
  Activity,
} from "lucide-react";

export const BURNOUT_NIVEL_CONFIG = {
  baixo: {
    color: 'text-success',
    bgColor: 'bg-success/10',
    borderColor: 'border-success/30',
    label: 'Baixo Risco',
    icon: '✓',
    chartColor: 'hsl(142, 76%, 36%)',
  },
  moderado: {
    color: 'text-warning',
    bgColor: 'bg-warning/10',
    borderColor: 'border-warning/30',
    label: 'Atenção',
    icon: '⚠',
    chartColor: 'hsl(38, 92%, 50%)',
  },
  alto: {
    color: 'text-orange-500',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    label: 'Alto Risco',
    icon: '🔥',
    chartColor: 'hsl(24, 95%, 53%)',
  },
  critico: {
    color: 'text-destructive',
    bgColor: 'bg-destructive/10',
    borderColor: 'border-destructive/30',
    label: 'Crítico',
    icon: '🚨',
    chartColor: 'hsl(0, 84%, 60%)',
  },
};

export const ENERGIA_NIVEL_CONFIG = {
  baixo: {
    color: 'text-destructive',
    bgColor: 'bg-destructive/10',
    borderColor: 'border-destructive/30',
    label: 'Crítico',
    icon: '⚠',
    chartColor: 'hsl(0, 84%, 60%)',
  },
  moderado: {
    color: 'text-warning',
    bgColor: 'bg-warning/10',
    borderColor: 'border-warning/30',
    label: 'Regular',
    icon: '⚡',
    chartColor: 'hsl(38, 92%, 50%)',
  },
  alto: {
    color: 'text-success',
    bgColor: 'bg-success/10',
    borderColor: 'border-success/30',
    label: 'Bom',
    icon: '✓',
    chartColor: 'hsl(142, 76%, 36%)',
  },
  excelente: {
    color: 'text-primary',
    bgColor: 'bg-primary/10',
    borderColor: 'border-primary/30',
    label: 'Excelente',
    icon: '⚡',
    chartColor: 'hsl(252, 59%, 48%)',
  },
};

export const BURNOUT_FATORES = [
  { 
    key: 'sobrecargaCognitiva', 
    label: 'Sobrecarga Cognitiva', 
    icon: TrendingDown, 
    description: 'Excesso de demandas mentais e complexidade das tarefas',
    detailedAnalysis: 'Analisamos a quantidade e complexidade dos riscos cognitivos identificados no ambiente de trabalho, incluindo demandas de atenção, memória e processamento de informações.',
    dataSource: ['Inventário de Riscos Cognitivos', 'Análise de Carga Mental'],
    sugestoes: [
      'Implementar rodízio de tarefas complexas',
      'Criar pausas programadas para recuperação mental',
      'Simplificar processos e procedimentos',
      'Implementar ferramentas de apoio cognitivo',
    ],
  },
  { 
    key: 'ritmoTrabalho', 
    label: 'Ritmo de Trabalho', 
    icon: Clock, 
    description: 'Velocidade e intensidade das atividades exigidas',
    detailedAnalysis: 'Avaliamos os riscos organizacionais relacionados ao ritmo, pressão por prazos e metas, intensidade das demandas e controle sobre o próprio trabalho.',
    dataSource: ['Riscos Organizacionais', 'Análise de Jornada'],
    sugestoes: [
      'Revisar metas e prazos irrealistas',
      'Balancear carga de trabalho entre equipes',
      'Implementar gestão de prioridades',
      'Avaliar necessidade de contratações',
    ],
  },
  { 
    key: 'faltaPausas', 
    label: 'Falta de Pausas', 
    icon: AlertTriangle, 
    description: 'Ausência de intervalos adequados para recuperação',
    detailedAnalysis: 'Consideramos as ações pendentes relacionadas a pausas e recuperação, assim como a existência de políticas e práticas de descanso durante a jornada.',
    dataSource: ['Ações Pendentes', 'Política de Pausas'],
    sugestoes: [
      'Implementar pausas ativas obrigatórias',
      'Criar espaços de descanso adequados',
      'Estabelecer política formal de pausas',
      'Monitorar intervalos por sistema',
    ],
  },
  { 
    key: 'humorNegativo', 
    label: 'Humor Negativo', 
    icon: TrendingDown, 
    description: 'Presença de estados emocionais negativos relatados',
    detailedAnalysis: 'Monitoramos os registros de humor diário dos colaboradores, identificando padrões de estresse, cansaço, ansiedade e desânimo nos últimos 7 dias.',
    dataSource: ['Humor Diário', 'Registros dos últimos 7 dias'],
    sugestoes: [
      'Realizar escuta ativa com gestores',
      'Oferecer apoio psicológico',
      'Investigar causas de insatisfação',
      'Promover ações de bem-estar',
    ],
  },
  { 
    key: 'denuncias', 
    label: 'Denúncias/Ocorrências', 
    icon: MessageSquareWarning, 
    description: 'Registros na ouvidoria relacionados ao ambiente',
    detailedAnalysis: 'Analisamos as manifestações recebidas pela ouvidoria, incluindo denúncias, reclamações e sugestões relacionadas ao ambiente de trabalho e relações interpessoais.',
    dataSource: ['Ouvidoria', 'Ocorrências em aberto'],
    sugestoes: [
      'Investigar denúncias pendentes',
      'Implementar ações corretivas',
      'Reforçar canais de comunicação',
      'Capacitar lideranças',
    ],
  },
  { 
    key: 'exigenciasEmocionais', 
    label: 'Exigências Emocionais', 
    icon: Heart, 
    description: 'Demandas de controle emocional no trabalho',
    detailedAnalysis: 'Combinamos indicadores de humor negativo com riscos cognitivos para avaliar a carga emocional exigida nas atividades laborais.',
    dataSource: ['Humor Diário', 'Riscos Cognitivos'],
    sugestoes: [
      'Oferecer treinamento de inteligência emocional',
      'Criar grupos de apoio entre pares',
      'Revisar atribuições de funções de alto contato',
      'Implementar supervisão técnica',
    ],
  },
] as const;

export const BOREOUT_FATORES = [
  { 
    key: 'baixoDesafio', 
    label: 'Baixo Desafio', 
    icon: Target, 
    description: 'Tarefas abaixo da capacidade do colaborador',
    detailedAnalysis: 'Avaliamos se há subutilização das competências dos colaboradores, analisando a relação entre capacidades identificadas e complexidade das tarefas atribuídas.',
    dataSource: ['Inventário de Riscos', 'Ações Cadastradas'],
    sugestoes: [
      'Mapear competências e realocá-las',
      'Criar projetos especiais desafiadores',
      'Implementar job enrichment',
      'Oferecer oportunidades de desenvolvimento',
    ],
  },
  { 
    key: 'repetitividade', 
    label: 'Repetitividade', 
    icon: RefreshCw, 
    description: 'Monotonia e falta de variabilidade nas atividades',
    detailedAnalysis: 'Analisamos riscos cognitivos relacionados à monotonia, avaliando a diversidade de tarefas e estímulos no ambiente de trabalho.',
    dataSource: ['Riscos Cognitivos', 'Análise de Tarefas'],
    sugestoes: [
      'Implementar rodízio de atividades',
      'Automatizar tarefas repetitivas',
      'Criar variação nas rotinas',
      'Enriquecer postos de trabalho',
    ],
  },
  { 
    key: 'faltaSentido', 
    label: 'Falta de Sentido', 
    icon: Minus, 
    description: 'Dificuldade em perceber propósito no trabalho',
    detailedAnalysis: 'Correlacionamos indicadores de humor com a percepção de propósito, avaliando se os colaboradores compreendem a importância de suas contribuições.',
    dataSource: ['Humor Diário', 'Clima Organizacional'],
    sugestoes: [
      'Comunicar propósito e impacto do trabalho',
      'Conectar tarefas aos objetivos maiores',
      'Promover reconhecimento',
      'Envolver em decisões',
    ],
  },
  { 
    key: 'apatia', 
    label: 'Apatia Emocional', 
    icon: Smile, 
    description: 'Indiferença e desinteresse pelas atividades',
    detailedAnalysis: 'Monitoramos a frequência de registros de humor neutro ou indiferente, que podem indicar desconexão emocional com o trabalho.',
    dataSource: ['Humor Diário', 'Taxa de Neutralidade'],
    sugestoes: [
      'Realizar conversas individuais',
      'Investigar causas da apatia',
      'Criar momentos de celebração',
      'Promover conexões interpessoais',
    ],
  },
  { 
    key: 'desconexao', 
    label: 'Desconexão com Equipe', 
    icon: Users, 
    description: 'Isolamento e falta de pertencimento',
    detailedAnalysis: 'Avaliamos indicadores de integração social, analisando a participação em atividades coletivas e a percepção de pertencimento ao grupo.',
    dataSource: ['Humor Positivo', 'Engajamento Social'],
    sugestoes: [
      'Promover team building',
      'Criar rituais de integração',
      'Facilitar colaboração entre áreas',
      'Estabelecer mentoria entre pares',
    ],
  },
] as const;

export const ENERGIA_FATORES = [
  { 
    key: 'vitalidade', 
    label: 'Vitalidade da Equipe', 
    icon: Heart, 
    description: 'Energia física e mental para executar tarefas',
    detailedAnalysis: 'Medimos a vitalidade através dos registros de humor positivo, avaliando a disposição e energia demonstrada pelos colaboradores.',
    dataSource: ['Humor Diário', 'Registros Positivos'],
    sugestoes: [
      'Promover atividades físicas',
      'Melhorar qualidade do ambiente',
      'Incentivar hábitos saudáveis',
      'Criar programa de qualidade de vida',
    ],
  },
  { 
    key: 'engajamento', 
    label: 'Engajamento', 
    icon: Activity, 
    description: 'Envolvimento ativo e comprometimento',
    detailedAnalysis: 'Calculamos o engajamento combinando taxa de conclusão de ações com indicadores positivos de humor, refletindo o comprometimento ativo.',
    dataSource: ['Ações Concluídas', 'Humor Positivo'],
    sugestoes: [
      'Reconhecer realizações publicamente',
      'Dar autonomia e responsabilidade',
      'Alinhar objetivos pessoais e organizacionais',
      'Promover participação em decisões',
    ],
  },
  { 
    key: 'presencaPsicologica', 
    label: 'Presença Psicológica', 
    icon: Sparkles, 
    description: 'Atenção plena e foco nas atividades',
    detailedAnalysis: 'Avaliamos a presença psicológica considerando a ausência de fatores negativos como humor ruim e denúncias abertas que indicam desconexão.',
    dataSource: ['Humor Negativo', 'Denúncias Abertas'],
    sugestoes: [
      'Implementar práticas de mindfulness',
      'Reduzir distrações no ambiente',
      'Criar ambientes de foco',
      'Promover gestão do tempo',
    ],
  },
  { 
    key: 'sustentabilidade', 
    label: 'Sustentabilidade', 
    icon: Zap, 
    description: 'Capacidade de manter o desempenho ao longo do tempo',
    detailedAnalysis: 'Avaliamos a sustentabilidade da energia considerando o nível de burnout - quanto menor o risco de burnout, maior a sustentabilidade.',
    dataSource: ['Índice de Burnout', 'Tendência Histórica'],
    sugestoes: [
      'Equilibrar demandas e recursos',
      'Promover recuperação adequada',
      'Monitorar sinais de esgotamento',
      'Criar cultura de cuidado',
    ],
  },
] as const;
