-- ============================================================================
-- CONFERENCIA: as telas tem lastro no banco de PRODUCAO?
--
-- POR QUE ESTE ARQUIVO
-- As telas de teste, de homologacao e de producao sao construidas do MESMO
-- codigo; o que muda entre elas e so a qual banco apontam. Ja o BANCO de cada
-- ambiente e diferente: no de teste as migrations chegam sozinhas, e no de
-- producao so chega o que e entregue a mao. Entao uma tela pode existir e o
-- banco de producao nao ter a peca que ela chama — a tela publica e quebra no
-- uso.
--
-- O QUE ELE FAZ
-- Le do proprio codigo das telas os nomes que elas chamam — 65 funcoes e
-- 190 tabelas/visoes — e confere um a um se existem NESTE banco.
--
-- COMO LER
--   * lista vazia (so a linha RESUMO com OK): todas as telas tem lastro;
--   * linhas FALTA: sao exatamente as pecas ausentes. Cada uma corresponde a
--     uma tela que vai falhar no uso. A coluna modulo ajuda a ver o tamanho do
--     estrago por area.
--
-- O QUE ELE NAO ALCANCA
-- Chamada montada dinamicamente no codigo (nome em variavel) nao aparece aqui,
-- nem coluna que falta numa tabela que existe. Ausencia de linha FALTA nao e
-- garantia absoluta de que nada quebra — e a eliminacao da causa mais comum.
-- Os depositos de arquivo (storage) tambem ficam de fora: sao outro subsistema.
--
-- SOMENTE LEITURA. Nao cria, nao altera e nao apaga nada.
-- ============================================================================

WITH usado (tipo, nome) AS MATERIALIZED (
  VALUES
    ('funcao', 'assinar_manual_funcao_publica'),
    ('funcao', 'assinar_ordem_servico_publica'),
    ('funcao', 'atualizar_cliente_por_onboarding_token'),
    ('funcao', 'atualizar_convite_por_token'),
    ('funcao', 'atualizar_documento_link_por_token'),
    ('funcao', 'buscar_campanha_por_token_publico'),
    ('funcao', 'buscar_cliente_por_activation_token'),
    ('funcao', 'buscar_cliente_por_onboarding_token'),
    ('funcao', 'buscar_colaborador_por_cpf'),
    ('funcao', 'buscar_contratos_por_cliente'),
    ('funcao', 'buscar_convite_por_token'),
    ('funcao', 'buscar_doc_links_por_cliente'),
    ('funcao', 'buscar_documento_link_por_token'),
    ('funcao', 'buscar_ponto_link_por_token'),
    ('funcao', 'buscar_profissionais_proximos_publico'),
    ('funcao', 'colaborador_tem_vinculos'),
    ('funcao', 'consolidar_ponto_dia_todos'),
    ('funcao', 'contar_colaboradores_por_empresa'),
    ('funcao', 'contar_respondentes_por_ghe'),
    ('funcao', 'delete_empresa_segura'),
    ('funcao', 'desconsiderar_marcacao_ponto'),
    ('funcao', 'ensure_admissao_documentos_by_token'),
    ('funcao', 'epi_atualizar_estoque_local_otimista'),
    ('funcao', 'epi_atualizar_estoque_otimista'),
    ('funcao', 'feriado_tabela_duplicar'),
    ('funcao', 'finalizar_admissao_by_token'),
    ('funcao', 'get_admissao_by_token'),
    ('funcao', 'get_admissao_documentos_by_token'),
    ('funcao', 'get_entrevista_by_token'),
    ('funcao', 'inativar_colaborador'),
    ('funcao', 'list_entrevista_mensagens_by_token'),
    ('funcao', 'listar_justificativas_externo'),
    ('funcao', 'listar_ponto_externo'),
    ('funcao', 'listar_ponto_externo_cpf'),
    ('funcao', 'obter_assinatura_manual_publica'),
    ('funcao', 'obter_contrato_publico'),
    ('funcao', 'obter_ordem_servico_publica'),
    ('funcao', 'ponto_link_registrar_tentativa'),
    ('funcao', 'ponto_link_renovar'),
    ('funcao', 'ponto_retificar_marcacao'),
    ('funcao', 'proximo_tipo_marcacao_externo'),
    ('funcao', 'proximo_tipo_marcacao_externo_cpf'),
    ('funcao', 'registrar_assinatura_contrato'),
    ('funcao', 'registrar_ponto_externo'),
    ('funcao', 'registrar_ponto_externo_cpf'),
    ('funcao', 'salvar_resposta_anonima_campanha'),
    ('funcao', 'salvar_resposta_por_token_participacao'),
    ('funcao', 'salvar_resposta_psicossocial'),
    ('funcao', 'seed_psicossocial_riscos_padrao'),
    ('funcao', 'solicitar_ajustes_ponto_externo_batch'),
    ('funcao', 'solicitar_ajustes_ponto_externo_cpf_batch'),
    ('funcao', 'superadmin_delete_tenant'),
    ('funcao', 'superadmin_global_stats'),
    ('funcao', 'superadmin_growth_series'),
    ('funcao', 'superadmin_list_all_empresas'),
    ('funcao', 'superadmin_list_tenant_users'),
    ('funcao', 'superadmin_psicossocial_overview'),
    ('funcao', 'superadmin_set_principal_empresa'),
    ('funcao', 'superadmin_tenants_list'),
    ('funcao', 'superadmin_tenants_status'),
    ('funcao', 'superadmin_usuarios_global'),
    ('funcao', 'update_admissao_documento_by_token'),
    ('funcao', 'update_admissao_foto_by_token'),
    ('funcao', 'validar_cpf_colaborador_campanha'),
    ('funcao', 'validar_token_participacao'),
    ('tabela', 'academia_aulas'),
    ('tabela', 'academia_badges'),
    ('tabela', 'academia_categorias'),
    ('tabela', 'academia_favoritos'),
    ('tabela', 'academia_modulos'),
    ('tabela', 'academia_progresso'),
    ('tabela', 'academia_treinamentos'),
    ('tabela', 'academia_xp'),
    ('tabela', 'admissao_documentos'),
    ('tabela', 'admissao_historico'),
    ('tabela', 'admissao_workflow'),
    ('tabela', 'admissoes'),
    ('tabela', 'afastamentos'),
    ('tabela', 'afastamentos_pendencias'),
    ('tabela', 'alertas_saude'),
    ('tabela', 'atestados'),
    ('tabela', 'audit_logs'),
    ('tabela', 'avaliacao_9box'),
    ('tabela', 'avaliacao_ciclos'),
    ('tabela', 'avaliacao_feedbacks'),
    ('tabela', 'avaliacao_respostas'),
    ('tabela', 'avaliacao_templates'),
    ('tabela', 'bem_estar_gratidao'),
    ('tabela', 'bem_estar_respostas'),
    ('tabela', 'beneficios_colaboradores'),
    ('tabela', 'blog_posts'),
    ('tabela', 'cargos'),
    ('tabela', 'cbo_ocupacoes'),
    ('tabela', 'condicoes_especiais_trabalho'),
    ('tabela', 'cultura_acoes'),
    ('tabela', 'cultura_config'),
    ('tabela', 'cultura_datas'),
    ('tabela', 'cultura_marcos'),
    ('tabela', 'cultura_preferencias'),
    ('tabela', 'cultura_rituais'),
    ('tabela', 'departamentos'),
    ('tabela', 'desvios_seguranca'),
    ('tabela', 'documento_audit_log'),
    ('tabela', 'documento_pastas'),
    ('tabela', 'documentos'),
    ('tabela', 'empresa_cadastro'),
    ('tabela', 'empresa_import_pendencias'),
    ('tabela', 'empresa_obrigacoes'),
    ('tabela', 'epi_categorias'),
    ('tabela', 'epi_cets'),
    ('tabela', 'epi_config'),
    ('tabela', 'epi_entregas'),
    ('tabela', 'epi_estoque_local'),
    ('tabela', 'epi_locais_estoque'),
    ('tabela', 'epi_movimentacoes'),
    ('tabela', 'epi_nf_itens'),
    ('tabela', 'epi_notas_fiscais'),
    ('tabela', 'epi_tamanhos'),
    ('tabela', 'epi_tipos'),
    ('tabela', 'epis'),
    ('tabela', 'ergonomia_acoes'),
    ('tabela', 'ergonomia_analises'),
    ('tabela', 'ergonomia_evidencias'),
    ('tabela', 'ergonomia_itens_nr17'),
    ('tabela', 'ergonomia_riscos'),
    ('tabela', 'esocial_certificados'),
    ('tabela', 'esocial_transmissoes'),
    ('tabela', 'evento_sst_acoes'),
    ('tabela', 'evento_sst_anexos'),
    ('tabela', 'eventos_sst'),
    ('tabela', 'feed_comentarios'),
    ('tabela', 'feed_posts'),
    ('tabela', 'feed_reacoes'),
    ('tabela', 'feriado_excecao'),
    ('tabela', 'feriado_folga_compensatoria'),
    ('tabela', 'feriado_tabela_empresas'),
    ('tabela', 'feriado_tabela_itens'),
    ('tabela', 'feriado_tabelas'),
    ('tabela', 'feriados'),
    ('tabela', 'ferias_assinatura_links'),
    ('tabela', 'ferias_historico'),
    ('tabela', 'ferias_solicitacoes'),
    ('tabela', 'filiais'),
    ('tabela', 'folha_alertas_prazo'),
    ('tabela', 'folha_cct'),
    ('tabela', 'folha_itens'),
    ('tabela', 'funcao_cets'),
    ('tabela', 'funcao_epis'),
    ('tabela', 'gaf_usuarios_perfis'),
    ('tabela', 'grupos_economicos'),
    ('tabela', 'hub_calendario_envios'),
    ('tabela', 'hub_calendario_status'),
    ('tabela', 'hub_certidoes'),
    ('tabela', 'hub_checklist_templates'),
    ('tabela', 'hub_competencias'),
    ('tabela', 'hub_config'),
    ('tabela', 'hub_contabilidades'),
    ('tabela', 'hub_documentos'),
    ('tabela', 'hub_guias'),
    ('tabela', 'hub_historico'),
    ('tabela', 'hub_processo_checklist'),
    ('tabela', 'hub_processo_comentarios'),
    ('tabela', 'hub_processo_documentos'),
    ('tabela', 'hub_processo_historico'),
    ('tabela', 'hub_processos'),
    ('tabela', 'humor_diario'),
    ('tabela', 'humor_historico'),
    ('tabela', 'jornada_alertas'),
    ('tabela', 'jornada_analises'),
    ('tabela', 'jornada_documentos'),
    ('tabela', 'jornada_importacoes'),
    ('tabela', 'jornada_parametros'),
    ('tabela', 'jornada_templates_mapeamento'),
    ('tabela', 'landing_leads'),
    ('tabela', 'landing_vagas'),
    ('tabela', 'lead_interacoes'),
    ('tabela', 'leads'),
    ('tabela', 'marketplace_afiliados_comissoes'),
    ('tabela', 'marketplace_audit_log'),
    ('tabela', 'marketplace_avaliacoes'),
    ('tabela', 'marketplace_categorias'),
    ('tabela', 'marketplace_contratacoes'),
    ('tabela', 'marketplace_denuncias'),
    ('tabela', 'marketplace_pacotes'),
    ('tabela', 'marketplace_profissionais'),
    ('tabela', 'marketplace_profissional_documentos'),
    ('tabela', 'marketplace_servicos'),
    ('tabela', 'meta_acao_tempo'),
    ('tabela', 'meta_acoes'),
    ('tabela', 'meta_aem'),
    ('tabela', 'meta_historico'),
    ('tabela', 'meta_okrs'),
    ('tabela', 'metas'),
    ('tabela', 'metas_checkins'),
    ('tabela', 'metas_configuracao'),
    ('tabela', 'metas_evidencias'),
    ('tabela', 'metas_indicadores'),
    ('tabela', 'metas_participantes'),
    ('tabela', 'metas_workflow_log'),
    ('tabela', 'ocorrencias'),
    ('tabela', 'okr_checkins'),
    ('tabela', 'ouvidoria'),
    ('tabela', 'ouvidoria_roteamento'),
    ('tabela', 'pdi_acoes'),
    ('tabela', 'pdi_assinatura_links'),
    ('tabela', 'pdi_checkins'),
    ('tabela', 'pdi_feedbacks'),
    ('tabela', 'pdi_metas'),
    ('tabela', 'pdis'),
    ('tabela', 'perfil_permissoes'),
    ('tabela', 'plano_acoes'),
    ('tabela', 'plano_comentarios'),
    ('tabela', 'plano_evidencias'),
    ('tabela', 'plano_historico'),
    ('tabela', 'plano_participantes'),
    ('tabela', 'plano_tarefas'),
    ('tabela', 'ponto_ajustes'),
    ('tabela', 'ponto_configuracao'),
    ('tabela', 'ponto_diario'),
    ('tabela', 'ponto_escalas'),
    ('tabela', 'ponto_ia_analises'),
    ('tabela', 'ponto_links'),
    ('tabela', 'profiles'),
    ('tabela', 'programa_validador_clientes'),
    ('tabela', 'programa_validador_contratos'),
    ('tabela', 'programa_validador_documento_links'),
    ('tabela', 'programa_validador_documentos'),
    ('tabela', 'programa_validador_historico'),
    ('tabela', 'psicossocial_alertas'),
    ('tabela', 'questionario_psicossocial_campanhas'),
    ('tabela', 'psicossocial_consentimentos'),
    ('tabela', 'psicossocial_entrevistas'),
    ('tabela', 'psicossocial_ghe'),
    ('tabela', 'psicossocial_ghe_cargos'),
    ('tabela', 'psicossocial_indice_confiabilidade'),
    ('tabela', 'psicossocial_participacoes'),
    ('tabela', 'questionario_psicossocial_campanhas'),
    ('tabela', 'questionario_psicossocial_convites'),
    ('tabela', 'questionario_psicossocial_respostas'),
    ('tabela', 'sst_documentos'),
    ('tabela', 'superadmins'),
    ('tabela', 'system_manual'),
    ('tabela', 'tenants'),
    ('tabela', 'terceiro_documentos'),
    ('tabela', 'trilha_modulos'),
    ('tabela', 'trilha_terceiro_progresso'),
    ('tabela', 'trilhas'),
    ('tabela', 'user_roles'),
    ('tabela', 'usuario_audit_log'),
    ('tabela', 'usuario_vinculos'),
    ('tabela', 'usuarios_base'),
    ('tabela', 'youreyes_agentes'),
    ('tabela', 'youreyes_documentos'),
    ('tabela', 'youreyes_execucoes')
),
estado AS MATERIALIZED (
  SELECT u.tipo, u.nome,
         CASE u.tipo
           WHEN 'funcao' THEN EXISTS (SELECT 1 FROM pg_proc p
                                       JOIN pg_namespace n ON n.oid = p.pronamespace
                                      WHERE n.nspname = 'public' AND p.proname = u.nome)
           WHEN 'tabela' THEN to_regclass('public.' || u.nome) IS NOT NULL
         END AS existe
  FROM usado u
)
SELECT 1 AS ordem,
       'FALTA'::text                                  AS situacao,
       tipo                                           AS tipo,
       nome                                           AS peca,
       CASE
         WHEN nome LIKE 'ponto%'      THEN 'Ponto'
         WHEN nome LIKE 'epi%'        THEN 'EPI'
         WHEN nome LIKE 'folha%'      THEN 'Folha'
         WHEN nome LIKE 'ferias%'     THEN 'Ferias'
         WHEN nome LIKE 'psicossocial%' THEN 'Psicossocial'
         WHEN nome LIKE 'afastament%' THEN 'Afastamentos'
         WHEN nome LIKE 'admiss%'     THEN 'Admissoes'
         WHEN nome LIKE 'beneficio%'  THEN 'Beneficios'
         WHEN nome LIKE 'ergonomia%'  THEN 'Ergonomia'
         WHEN nome LIKE 'hub%'        THEN 'Hub contabil'
         WHEN nome LIKE 'trilha%' OR nome LIKE 'academia%' THEN 'Treinamentos'
         WHEN nome LIKE 'qa%'         THEN 'Bancada de QA'
         ELSE 'Outros'
       END                                            AS modulo
FROM estado WHERE NOT existe
UNION ALL
SELECT 0, 'RESUMO',
       (SELECT count(*) FROM estado WHERE existe)::text || ' de '
         || (SELECT count(*) FROM estado)::text || ' pecas presentes',
       (SELECT count(*) FROM estado WHERE NOT existe)::text || ' faltando',
       CASE WHEN (SELECT count(*) FROM estado WHERE NOT existe) = 0
            THEN 'OK — as telas tem lastro neste banco'
            ELSE 'CONFERIR — as pecas listadas abaixo nao existem aqui' END
ORDER BY ordem, modulo, tipo, peca;
