-- ============================================================================
-- EXTRATOR DE DDL — subsistema de PLANOS / ASSINATURAS / ENTITLEMENTS
--
-- SOMENTE LEITURA. So le o catalogo do banco (pg_catalog / information_schema).
-- Nao cria, nao altera e nao apaga NADA. Pode rodar quantas vezes quiser.
--
-- ONDE COLAR
-- No SQL Editor da PRODUCAO (diayjpsrcerycycyaxst). E o unico lugar onde esses
-- objetos existem hoje: eles foram criados fora das migrations (provavelmente
-- pelo Lovable) e nunca entraram no repositorio, entao a homologacao/teste nao
-- os tem. Este extrator LE a estrutura deles para eu reconstruir uma migration
-- de captura (CREATE ... IF NOT EXISTS) e faze-los descer para desenvolvimento
-- e homologacao pela esteira normal. A producao NAO e tocada — e leitura pura.
--
-- O QUE FAZER COM A SAIDA
-- Copie a grade inteira (coluna "ddl") e me cole aqui. Vem uma linha por objeto,
-- na ordem em que precisam ser recriados (tipos enum, tabelas, constraints,
-- indices, RLS, politicas, funcoes, gatilhos).
--
-- COMO LER
--   ordem      = ordem de recriacao (0=enum ... 7=gatilho)
--   categoria  = que tipo de objeto e
--   objeto     = nome
--   ddl        = o comando que recria aquele objeto
-- Se algum bloco vier vazio, aquele tipo simplesmente nao existe no subsistema.
-- ============================================================================

WITH
alvo_tabelas(t) AS (
  VALUES ('plans'), ('plan_prices'), ('plan_entitlements'),
         ('subscriptions'), ('subscription_overrides'), ('usage_counters'),
         ('features'), ('entitlement_gated_tables'),
         ('entitlement_audit_log'), ('entitlement_denials_log')
),
alvo_funcoes(f) AS (
  VALUES ('tenant_has_feature'), ('entitlement_can_use'), ('entitlement_resolve'),
         ('entitlement_apply_policies'), ('entitlement_build_statements'),
         ('log_entitlement_denial'), ('set_updated_at')
),
-- oids das tabelas alvo (existentes)
tab AS MATERIALIZED (
  SELECT c.oid, c.relname, c.relrowsecurity, c.relforcerowsecurity
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
  WHERE c.relkind = 'r' AND c.relname IN (SELECT t FROM alvo_tabelas)
),
-- 0) ENUMS usados por colunas das tabelas alvo
enums AS (
  SELECT DISTINCT ty.oid, ty.typname
  FROM tab
  JOIN pg_attribute a ON a.attrelid = tab.oid AND a.attnum > 0 AND NOT a.attisdropped
  JOIN pg_type ty ON ty.oid = a.atttypid AND ty.typtype = 'e'
  JOIN pg_namespace tn ON tn.oid = ty.typnamespace AND tn.nspname = 'public'
),
enums_ddl AS (
  SELECT 0 AS ordem, 'enum'::text AS categoria, e.typname AS objeto,
         'CREATE TYPE public.' || quote_ident(e.typname) || ' AS ENUM ('
         || (SELECT string_agg(quote_literal(en.enumlabel), ', ' ORDER BY en.enumsortorder)
             FROM pg_enum en WHERE en.enumtypid = e.oid)
         || ');' AS ddl
  FROM enums e
),
-- 1) TABELAS (colunas, com NOT NULL / DEFAULT / IDENTITY / GENERATED)
tabelas_ddl AS (
  SELECT 1 AS ordem, 'tabela'::text AS categoria, tab.relname AS objeto,
         'CREATE TABLE IF NOT EXISTS public.' || quote_ident(tab.relname) || E' (\n'
         || string_agg(
              '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
              || CASE a.attidentity
                   WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                   WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
                   ELSE '' END
              || CASE WHEN a.attgenerated = 's'
                      THEN ' GENERATED ALWAYS AS (' || COALESCE(pg_get_expr(ad.adbin, ad.adrelid), '') || ') STORED'
                      WHEN a.attidentity = '' AND ad.adbin IS NOT NULL
                      THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
                      ELSE '' END
              || CASE WHEN a.attnotnull AND a.attidentity = '' AND a.attgenerated = '' THEN ' NOT NULL' ELSE '' END,
              E',\n' ORDER BY a.attnum)
         || E'\n);' AS ddl
  FROM tab
  JOIN pg_attribute a ON a.attrelid = tab.oid AND a.attnum > 0 AND NOT a.attisdropped
  LEFT JOIN pg_attrdef ad ON ad.adrelid = tab.oid AND ad.adnum = a.attnum
  GROUP BY tab.relname
),
-- 2) CONSTRAINTS (PK, FK, UNIQUE, CHECK) via pg_get_constraintdef
constraints_ddl AS (
  SELECT 2 AS ordem,
         'constraint:' || CASE con.contype WHEN 'p' THEN 'pk' WHEN 'f' THEN 'fk'
                                            WHEN 'u' THEN 'unique' WHEN 'c' THEN 'check'
                                            ELSE con.contype::text END AS categoria,
         tab.relname || '.' || con.conname AS objeto,
         'ALTER TABLE public.' || quote_ident(tab.relname)
         || ' ADD CONSTRAINT ' || quote_ident(con.conname) || ' '
         || pg_get_constraintdef(con.oid) || ';' AS ddl
  FROM pg_constraint con
  JOIN tab ON tab.oid = con.conrelid
),
-- 3) INDICES que NAO sao backing de constraint (esses ja vem no passo 2)
indices_ddl AS (
  SELECT 3 AS ordem, 'indice'::text AS categoria, ic.relname AS objeto,
         pg_get_indexdef(i.indexrelid) || ';' AS ddl
  FROM pg_index i
  JOIN tab ON tab.oid = i.indrelid
  JOIN pg_class ic ON ic.oid = i.indexrelid
  WHERE NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = i.indexrelid)
),
-- 4) LIGAR RLS (e FORCE, quando for o caso)
rls_ddl AS (
  SELECT 4 AS ordem, 'rls'::text AS categoria, tab.relname AS objeto,
         'ALTER TABLE public.' || quote_ident(tab.relname) || ' ENABLE ROW LEVEL SECURITY;'
         || CASE WHEN tab.relforcerowsecurity
                 THEN ' ALTER TABLE public.' || quote_ident(tab.relname) || ' FORCE ROW LEVEL SECURITY;'
                 ELSE '' END AS ddl
  FROM tab
  WHERE tab.relrowsecurity
),
-- 5) POLITICAS RLS
politicas_ddl AS (
  SELECT 5 AS ordem, 'politica'::text AS categoria,
         p.tablename || '.' || p.policyname AS objeto,
         'CREATE POLICY ' || quote_ident(p.policyname) || ' ON public.' || quote_ident(p.tablename)
         || ' AS ' || p.permissive
         || ' FOR ' || p.cmd
         || ' TO ' || array_to_string(p.roles, ', ')
         || COALESCE(' USING (' || p.qual || ')', '')
         || COALESCE(' WITH CHECK (' || p.with_check || ')', '')
         || ';' AS ddl
  FROM pg_policies p
  WHERE p.schemaname = 'public' AND p.tablename IN (SELECT t FROM alvo_tabelas)
),
-- 6) FUNCOES (corpo completo)
funcoes_ddl AS (
  SELECT 6 AS ordem, 'funcao'::text AS categoria,
         p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' AS objeto,
         pg_get_functiondef(p.oid) || ';' AS ddl
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace AND n.nspname = 'public'
  WHERE p.prokind IN ('f', 'p')
    AND ( p.proname IN (SELECT f FROM alvo_funcoes)
          OR p.proname LIKE 'entitlement%' )
),
-- 7) GATILHOS nas tabelas alvo
gatilhos_ddl AS (
  SELECT 7 AS ordem, 'gatilho'::text AS categoria,
         tab.relname || '.' || tg.tgname AS objeto,
         pg_get_triggerdef(tg.oid) || ';' AS ddl
  FROM pg_trigger tg
  JOIN tab ON tab.oid = tg.tgrelid
  WHERE NOT tg.tgisinternal AND tg.tgname <> 'qa_guarda_cercado'
),
tudo AS (
  SELECT * FROM enums_ddl
  UNION ALL SELECT * FROM tabelas_ddl
  UNION ALL SELECT * FROM constraints_ddl
  UNION ALL SELECT * FROM indices_ddl
  UNION ALL SELECT * FROM rls_ddl
  UNION ALL SELECT * FROM politicas_ddl
  UNION ALL SELECT * FROM funcoes_ddl
  UNION ALL SELECT * FROM gatilhos_ddl
)
SELECT ordem, categoria, objeto, ddl
FROM tudo
ORDER BY ordem, objeto;
