WITH
alvo_tabelas(t) AS (
  VALUES ('plans'), ('plan_prices'), ('plan_entitlements'),
         ('subscriptions'), ('subscription_overrides'), ('usage_counters'),
         ('features'), ('entitlement_gated_tables'),
         ('entitlement_audit_log'), ('entitlement_denials_log')
),
alvo_funcoes(f) AS (
  VALUES ('tenant_has_feature'), ('entitlement_can_use'), ('entitlement_resolve'),
         ('entitlement_apply_policies'), ('entitlement_build_statements'),
         ('log_entitlement_denial'), ('set_updated_at')
),
tab AS MATERIALIZED (
  SELECT c.oid, c.relname, c.relrowsecurity, c.relforcerowsecurity
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
  WHERE c.relkind = 'r' AND c.relname IN (SELECT t FROM alvo_tabelas)
),
enums AS (
  SELECT DISTINCT ty.oid, ty.typname
  FROM tab
  JOIN pg_attribute a ON a.attrelid = tab.oid AND a.attnum > 0 AND NOT a.attisdropped
  JOIN pg_type ty ON ty.oid = a.atttypid AND ty.typtype = 'e'
  JOIN pg_namespace tn ON tn.oid = ty.typnamespace AND tn.nspname = 'public'
),
enums_ddl AS (
  SELECT 0 AS ordem, 'tipo_enum'::text AS categoria, e.typname AS objeto,
         (SELECT string_agg(quote_literal(en.enumlabel), ', ' ORDER BY en.enumsortorder)
          FROM pg_enum en WHERE en.enumtypid = e.oid) AS detalhe
  FROM enums e
),
tabelas_ddl AS (
  SELECT 1 AS ordem, 'tabela'::text AS categoria, tab.relname AS objeto,
         string_agg(
              quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
              || CASE a.attidentity
                   WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                   WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
                   ELSE '' END
              || CASE WHEN a.attgenerated = 's'
                      THEN ' GENERATED ALWAYS AS (' || COALESCE(pg_get_expr(ad.adbin, ad.adrelid), '') || ') STORED'
                      WHEN a.attidentity = '' AND ad.adbin IS NOT NULL
                      THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
                      ELSE '' END
              || CASE WHEN a.attnotnull AND a.attidentity = '' AND a.attgenerated = '' THEN ' NOT NULL' ELSE '' END,
              ',' || chr(10) ORDER BY a.attnum) AS detalhe
  FROM tab
  JOIN pg_attribute a ON a.attrelid = tab.oid AND a.attnum > 0 AND NOT a.attisdropped
  LEFT JOIN pg_attrdef ad ON ad.adrelid = tab.oid AND ad.adnum = a.attnum
  GROUP BY tab.relname
),
constraints_ddl AS (
  SELECT 2 AS ordem,
         'restricao:' || CASE con.contype WHEN 'p' THEN 'pk' WHEN 'f' THEN 'fk'
                                          WHEN 'u' THEN 'unique' WHEN 'c' THEN 'check'
                                          ELSE con.contype::text END AS categoria,
         tab.relname || chr(46) || con.conname AS objeto,
         pg_get_constraintdef(con.oid) AS detalhe
  FROM pg_constraint con
  JOIN tab ON tab.oid = con.conrelid
),
indices_ddl AS (
  SELECT 3 AS ordem, 'indice'::text AS categoria, ic.relname AS objeto,
         pg_get_indexdef(i.indexrelid) AS detalhe
  FROM pg_index i
  JOIN tab ON tab.oid = i.indrelid
  JOIN pg_class ic ON ic.oid = i.indexrelid
  WHERE NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = i.indexrelid)
),
rls_ddl AS (
  SELECT 4 AS ordem, 'rls'::text AS categoria, tab.relname AS objeto,
         CASE WHEN tab.relforcerowsecurity THEN 'enable+force' ELSE 'enable' END AS detalhe
  FROM tab WHERE tab.relrowsecurity
),
politicas_ddl AS (
  SELECT 5 AS ordem, 'politica'::text AS categoria,
         p.tablename || chr(46) || p.policyname AS objeto,
         p.permissive || ' ~|~ ' || p.cmd || ' ~|~ ' || array_to_string(p.roles, ', ')
         || ' ~|~ ' || COALESCE(p.qual, '') || ' ~|~ ' || COALESCE(p.with_check, '') AS detalhe
  FROM pg_policies p
  WHERE p.schemaname = 'public' AND p.tablename IN (SELECT t FROM alvo_tabelas)
),
funcoes_ddl AS (
  SELECT 6 AS ordem, 'funcao'::text AS categoria,
         p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' AS objeto,
         pg_get_functiondef(p.oid) AS detalhe
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace AND n.nspname = 'public'
  WHERE p.prokind IN ('f', 'p')
    AND ( p.proname IN (SELECT f FROM alvo_funcoes)
          OR p.proname LIKE 'entitlement%' )
),
gatilhos_ddl AS (
  SELECT 7 AS ordem, 'gatilho'::text AS categoria,
         tab.relname || chr(46) || tg.tgname AS objeto,
         pg_get_triggerdef(tg.oid) AS detalhe
  FROM pg_trigger tg
  JOIN tab ON tab.oid = tg.tgrelid
  WHERE NOT tg.tgisinternal AND tg.tgname <> 'qa_guarda_cercado'
),
tudo AS (
  SELECT * FROM enums_ddl
  UNION ALL SELECT * FROM tabelas_ddl
  UNION ALL SELECT * FROM constraints_ddl
  UNION ALL SELECT * FROM indices_ddl
  UNION ALL SELECT * FROM rls_ddl
  UNION ALL SELECT * FROM politicas_ddl
  UNION ALL SELECT * FROM funcoes_ddl
  UNION ALL SELECT * FROM gatilhos_ddl
)
SELECT ordem, categoria, objeto, detalhe
FROM tudo
ORDER BY ordem, objeto
