-- =========================================================
-- NEUTRALIZADA — colisão com a consolidação v3
--
-- Esta migration implementava atraso por escala reescrevendo
-- consolidar_ponto_diario_manual. Em paralelo, a migration
-- 20260611010000_consolidacao_v3_escala_anomalia já havia
-- resolvido o mesmo problema de forma mais completa (atraso
-- por escala + detecção de anomalia de sequência + propagação
-- de empresa_id + política "sem escala não marca atraso").
--
-- Como esta rodaria DEPOIS da v3 e sobrescreveria a função,
-- foi esvaziada. A 20260611130000 reafirma a v3 para os
-- ambientes em que esta versão chegou a ser aplicada.
-- =========================================================
SELECT 1; -- no-op
